/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func GetBestOfGenre(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetBestOfGenreImpl(w, r)
}

func GetEpisode(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetEpisodeImpl(w, r)
}

func GetEpisodeRecommendationsBasedOnEpisode(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetEpisodeRecommendationsBasedOnEpisodeImpl(w, r)
}

func GetGenres(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetGenresImpl(w, r)
}

func GetPodcast(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetPodcastImpl(w, r)
}

func GetPodcastRecommendationsBasedOnPodcast(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetPodcastRecommendationsBasedOnPodcastImpl(w, r)
}

func GetSearchResults(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetSearchResultsImpl(w, r)
}

func GetTheBestPodcasts(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetTheBestPodcastsImpl(w, r)
}

func GetTimingResults(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetTimingResultsImpl(w, r)
}

func GetTopLevelGenres(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	GetTopLevelGenresImpl(w, r)
}

func GetUniqueId(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=UTF-8")
	GetUniqueIdImpl(w, r)
}

func LogTimingResultPost(w http.ResponseWriter, r *http.Request) {
	LogTimingResultImpl(w, r)
}

func Test(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=UTF-8")
	TestImpl(w, r)
}
