/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Genre struct {
	// Genre id
	Id int32 `json:"id,omitempty"`
	// Genre name.
	Name string `json:"name,omitempty"`
	// Parent genre id.
	ParentId int32 `json:"parent_id,omitempty"`
}
