/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PodcastSimple struct {

	IsClaimed bool `json:"is_claimed,omitempty"`

	Type_ *PodcastTypeField `json:"type,omitempty"`

	ExplicitContent bool `json:"explicit_content,omitempty"`

	Website string `json:"website,omitempty"`

	TotalEpisodes int32 `json:"total_episodes,omitempty"`

	EarliestPubDateMs int32 `json:"earliest_pub_date_ms,omitempty"`

	Rss string `json:"rss,omitempty"`

	LatestPubDateMs int32 `json:"latest_pub_date_ms,omitempty"`

	Title string `json:"title,omitempty"`

	Language string `json:"language,omitempty"`

	Description string `json:"description,omitempty"`

	Email string `json:"email,omitempty"`

	Image string `json:"image,omitempty"`

	Thumbnail string `json:"thumbnail,omitempty"`

	ListennotesUrl string `json:"listennotes_url,omitempty"`

	Id string `json:"id,omitempty"`

	Country string `json:"country,omitempty"`

	Publisher string `json:"publisher,omitempty"`

	ItunesId int32 `json:"itunes_id,omitempty"`

	LookingFor *PodcastLookingForField `json:"looking_for,omitempty"`

	Extra *PodcastExtraField `json:"extra,omitempty"`

	GenreIds *[]int32 `json:"genre_ids,omitempty"`

	ListenScore int32 `json:"listen_score,omitempty"`

	ListenScoreGlobalRank string `json:"listen_score_global_rank,omitempty"`
}
