/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShowExtra struct {
	// Url affiliated with this podcast
	Url1 string `json:"url1,omitempty"`
	// Url affiliated with this podcast
	Url2 string `json:"url2,omitempty"`
	// Url affiliated with this podcast
	Url3 string `json:"url3,omitempty"`
	// Google Podcasts url for this podcast
	GoogleUrl string `json:"google_url,omitempty"`
	// Spotify url for this podcast
	SpotifyUrl string `json:"spotify_url,omitempty"`
	// YouTube url affiliated with this podcast
	YoutubeUrl string `json:"youtube_url,omitempty"`
	// LinkedIn url affiliated with this podcast
	LinkedinUrl string `json:"linkedin_url,omitempty"`
	// WeChat username affiliated with this podcast
	WechatHandle string `json:"wechat_handle,omitempty"`
	// Patreon username affiliated with this podcast
	PatreonHandle string `json:"patreon_handle,omitempty"`
	// Twitter username affiliated with this podcast
	TwitterHandle string `json:"twitter_handle,omitempty"`
	// Facebook username affiliated with this podcast
	FacebookHandle string `json:"facebook_handle,omitempty"`
	// Instagram username affiliated with this podcast
	InstagramHandle string `json:"instagram_handle,omitempty"`
}
