/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PodcastMinimum struct {
	// Podcast id.
	Id string `json:"id,omitempty"`
	// Image url for this podcast's artwork. If you are using PRO plan, then it's a high resolution image (1400x1400). If you are using FREE plan, then it's the same as **thumbnail**, low resolution image (300x300). 
	Image string `json:"image,omitempty"`
	// Podcast name.
	Title string `json:"title,omitempty"`
	// Podcast publisher name.
	Publisher string `json:"publisher,omitempty"`
	// Thumbnail image url for this podcast's artwork (300x300).
	Thumbnail string `json:"thumbnail,omitempty"`
	// The url of this podcast on [ListenNotes.com](https://www.ListenNotes.com).
	ListennotesUrl string `json:"listennotes_url,omitempty"`
}
