/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// PodcastTypeField : The type of this podcast - episodic or serial.
type PodcastTypeField string

// List of PodcastTypeField
const (
	EPISODIC PodcastTypeField = "episodic"
	SERIAL PodcastTypeField = "serial"
)
