/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EpisodeSimplePodcast struct {

	Id string `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Publisher string `json:"publisher,omitempty"`

	Image string `json:"image,omitempty"`

	Thumbnail string `json:"thumbnail,omitempty"`

	ListennotesUrl string `json:"listennotes_url,omitempty"`
}
