/*
 * Podcast Recommender app
 *
 * This is the API for the podcast recommender app. The API used to get all data is Listen Notes (https://www.listennotes.com/api/)
 *
 * API version: 1.0.0
 * Contact: joren.sjongers@icloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShowLookingFor struct {
	// Whether this podcast is looking for guests.
	Guests bool `json:"guests,omitempty"`
	// Whether this podcast is looking for cohosts.
	Cohosts bool `json:"cohosts,omitempty"`
	// Whether this podcast is looking for sponsors.
	Sponsors bool `json:"sponsors,omitempty"`
	// Whether this podcast is looking for cross promotion opportunities with other podcasts.
	CrossPromotion bool `json:"cross_promotion,omitempty"`
}
