openapi: 3.0.1
info:
  title: Podcast Recommender app
  description: This is the API for the podcast recommender app. The API used to get
    all data is Listen Notes (https://www.listennotes.com/api/)
  contact:
    email: joren.sjongers@icloud.com
  version: 1.0.0
servers:
- url: //TODO/
paths:
  /test:
    get:
      summary: used to test whether the backend is running.
      description: returns 'Hello World'
      operationId: test
      responses:
        "200":
          description: succesful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_200'
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        test:
          type: string
          example: Hello World
      example:
        test: Hello World
x-original-swagger-version: "2.0"
